#include <isogrid.h>
#ifndef WRITEOBJ
#define WRITEOBJ 0
#endif

#if WRITEOBJ
#include <fstream>
#include <sstream>

#ifndef WRITEOBJ_PATH
#define WRITEOBJ_PATH "filename.obj"
#endif

#endif
int main()
{
  IsoGridInstance a;
  a.setInitResolution(16);
  a.executeCommands({ Commands::Maze });

  std::vector<IsoGridInstance::Face> faces;
  std::vector<IsoGridInstance::Vertex> vertices;
  a.getMesh(
      [&vertices](float x, float y, float z) {
        vertices.push_back({ x, y, z });
      },
      [&faces](int a, int b, int c, int d) {
        faces.push_back({ a, b, c, d });
      });

#if WRITEOBJ
  std::ofstream file(WRITEOBJ_PATH);
  std::stringstream objstr;
  objstr << "# generated by WB_CubeGridExporter\n";
  for (auto &vertex : vertices)
  {
    objstr << "v " << vertex.x << " " << vertex.y << " " << vertex.z << '\n';
  }
  for (auto &face : faces)
  {
    objstr << "f " << face.a << ' ' << face.b << ' ' << face.c << '\n';
    objstr << "f " << face.c << ' ' << face.d << ' ' << face.a << '\n';
  }
  file << objstr.str();
#endif

  return 0;
}
